# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('anaid', models.TextField(primary_key=True, serialize=False)),
                ('lumi', models.FloatField()),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPool',
            fields=[
                ('pool', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'analysis_pool',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='Normalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('norm', models.FloatField()),
                ('scalemc', models.IntegerField()),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
            ],
            options={
                'db_table': 'normalization',
            },
        ),
        migrations.CreateModel(
            name='Subpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('subanaid', models.IntegerField()),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
            ],
            options={
                'db_table': 'subpool',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
            ],
            options={
                'db_table': 'whitelist',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='pool',
            field=models.ForeignKey(blank=True, db_column='pool', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.AnalysisPool'),
        ),
        migrations.AlterUniqueTogether(
            name='subpool',
            unique_together=set([('anaid', 'pattern')]),
        ),
        migrations.AlterUniqueTogether(
            name='normalization',
            unique_together=set([('anaid', 'pattern')]),
        ),
    ]
