# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 13:41
from __future__ import unicode_literals

from django.db import migrations

def get_initial_contur_sql():
    with open('analyses.sql') as f:
        result = f.read()
    return result


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(get_initial_contur_sql()),
    ]
