# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_first_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSM_Model',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bsm_model',
            },
        ),
        migrations.CreateModel(
            name='Used_analyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
                ('modelname', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.BSM_Model')),
            ],
            options={
                'db_table': 'used_analyses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='used_analyses',
            unique_together=set([('anaid', 'modelname')]),
        ),
    ]
