# Generated by Django 2.0.5 on 2018-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_auto_20180809_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results_header',
            name='type',
        ),
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='090820181628', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='090820181628', max_length=50, primary_key=True, serialize=False),
        ),
    ]
