# Generated by Django 2.0.5 on 2018-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_auto_20180704_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='040720181304', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='ErrorBars',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='LineColor',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='Path',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='PolyMarker',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='Title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='Type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='XLabel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='YLabel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='xyd',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='yodamerge_scale',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='040720181304', max_length=50, primary_key=True, serialize=False),
        ),
    ]
