# Generated by Django 2.0.5 on 2018-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('runcard_name', models.CharField(default='220620181334', max_length=200, primary_key=True, serialize=False)),
                ('Model', models.CharField(choices=[('Dark_Matter_Test', 'Dark_Matter_Test'), ('test_model_2', 'test_model_2'), ('upload_test_2', 'upload_test_2'), ('upload_demo_3', 'upload_demo_3')], default='', max_length=200)),
                ('Parameter_Card', models.FileField(default='', upload_to='analyses/parameters-cards/')),
            ],
        ),
        migrations.CreateModel(
            name='histo1_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlow', models.FloatField()),
                ('xhigh', models.FloatField()),
                ('sumw', models.FloatField()),
                ('sumw2', models.FloatField()),
                ('sumwx', models.FloatField()),
                ('sumwx2', models.FloatField()),
                ('numEntries', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('key_word', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keywords_list',
            },
        ),
        migrations.CreateModel(
            name='Linked_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anaid', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
                ('key_word', models.ForeignKey(db_column='keyword', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Keyword')),
            ],
            options={
                'db_table': 'linked_keywords',
            },
        ),
        migrations.CreateModel(
            name='overflow_underflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(max_length=50)),
                ('sumw', models.FloatField()),
                ('sumw2', models.FloatField()),
                ('sumwx', models.FloatField()),
                ('sumwx2', models.FloatField()),
                ('sumwy', models.FloatField()),
                ('sumwy2', models.FloatField()),
                ('numEntries', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='profile1_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlow', models.FloatField()),
                ('xhigh', models.FloatField()),
                ('sumw', models.FloatField()),
                ('sumw2', models.FloatField()),
                ('sumwx', models.FloatField()),
                ('sumwx2', models.FloatField()),
                ('sumwy', models.FloatField()),
                ('sumwy2', models.FloatField()),
                ('numEntries', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='results_analyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xyd', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.Analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='results_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mc_ver', models.CharField(default='0.0.0', max_length=20)),
                ('contur_ver', models.CharField(default='0.0.0', max_length=20)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyses.results_header')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='results_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='analyses.results_header')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='runcard',
            fields=[
                ('runcard_name', models.CharField(default='220620181334', max_length=50, primary_key=True, serialize=False)),
                ('param_card', models.FileField(upload_to='analyses/parameters-cards/')),
                ('modelname', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.BSM_Model')),
            ],
            options={
                'db_table': 'runcard_export',
            },
        ),
        migrations.CreateModel(
            name='scatter1_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xval', models.FloatField()),
                ('xerr_n', models.FloatField()),
                ('xerr_p', models.FloatField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatter1', to='analyses.results_analyses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='scatter2_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xval', models.FloatField()),
                ('xerr_n', models.FloatField()),
                ('xerr_p', models.FloatField()),
                ('yval', models.FloatField()),
                ('yerr_n', models.FloatField()),
                ('yerr_p', models.FloatField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatter2', to='analyses.results_analyses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='scatter3_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xval', models.FloatField()),
                ('xerr_n', models.FloatField()),
                ('xerr_p', models.FloatField()),
                ('yval', models.FloatField()),
                ('yerr_n', models.FloatField()),
                ('yerr_p', models.FloatField()),
                ('zval', models.FloatField()),
                ('zerr_n', models.FloatField()),
                ('zerr_p', models.FloatField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scatter3', to='analyses.results_analyses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='upload_file',
            field=models.FileField(default='', upload_to='analyses/temp/'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_type',
            field=models.CharField(choices=[('Analyses', 'Analyses'), ('Analyses_Pool', 'Analyses Pool'), ('BSM_Model', 'BSM Model')], default='Analyses', max_length=20),
        ),
        migrations.AddField(
            model_name='results_header',
            name='runcard',
            field=models.ForeignKey(db_column='runcard_name', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.runcard'),
        ),
        migrations.AddField(
            model_name='results_analyses',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyses.results_position'),
        ),
        migrations.AddField(
            model_name='profile1_data',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='analyses.results_analyses'),
        ),
        migrations.AddField(
            model_name='overflow_underflow',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overunder', to='analyses.results_analyses'),
        ),
        migrations.AddField(
            model_name='histo1_data',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histo1', to='analyses.results_analyses'),
        ),
        migrations.AlterUniqueTogether(
            name='runcard',
            unique_together={('runcard_name', 'param_card')},
        ),
        migrations.AlterUniqueTogether(
            name='linked_keys',
            unique_together={('key_word', 'anaid')},
        ),
    ]
