# Generated by Django 2.0.5 on 2018-07-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_auto_20180704_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='040720181305', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='ScaledBy',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='area',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='results_analyses',
            name='mean',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='040720181305', max_length=50, primary_key=True, serialize=False),
        ),
    ]
