# Generated by Django 2.0.5 on 2018-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0009_auto_20180815_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='150820181007', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='150820181007', max_length=50, primary_key=True, serialize=False),
        ),
    ]
