# Generated by Django 2.0.5 on 2018-07-05 10:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0009_auto_20180704_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='overflow_underflow_histo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(max_length=50)),
                ('sumw', models.FloatField()),
                ('sumw2', models.FloatField()),
                ('sumwx', models.FloatField()),
                ('sumwx2', models.FloatField()),
                ('numEntries', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overunderhist', to='analyses.results_analyses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='overflow_underflow_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(max_length=50)),
                ('sumw', models.FloatField()),
                ('sumw2', models.FloatField()),
                ('sumwx', models.FloatField()),
                ('sumwx2', models.FloatField()),
                ('sumwy', models.FloatField()),
                ('sumwy2', models.FloatField()),
                ('numEntries', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overunderprof', to='analyses.results_analyses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='overflow_underflow',
            name='parent',
        ),
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='050720181039', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='050720181039', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='overflow_underflow',
        ),
    ]
