# Generated by Django 2.0.5 on 2018-08-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_auto_20180815_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ana_file',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='ana_file',
            name='linked_ana',
            field=models.ForeignKey(db_column='linked_ana', on_delete=django.db.models.deletion.CASCADE, to='analyses.ana_list'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pool',
            field=models.ForeignKey(blank=True, db_column='pool', null=True, on_delete=django.db.models.deletion.CASCADE, to='analyses.AnalysisPool'),
        ),
        migrations.AlterField(
            model_name='attached_files',
            name='parent',
            field=models.ForeignKey(db_column='results_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_header'),
        ),
        migrations.AlterField(
            model_name='attached_papers',
            name='parent',
            field=models.ForeignKey(db_column='results_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_header'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='dat_database',
            name='results_object',
            field=models.ForeignKey(db_column='results_position', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_position'),
        ),
        migrations.AlterField(
            model_name='dat_files',
            name='parent',
            field=models.ForeignKey(db_column='dat_database', on_delete=django.db.models.deletion.CASCADE, to='analyses.dat_database'),
        ),
        migrations.AlterField(
            model_name='download',
            name='Model',
            field=models.CharField(choices=[('Dark_Matter_Example', 'Dark_Matter_Example')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='150820181433', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='histo1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='histo_data',
            name='parent',
            field=models.ForeignKey(db_column='histo_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.histo_header'),
        ),
        migrations.AlterField(
            model_name='histo_header',
            name='results_object',
            field=models.ForeignKey(db_column='results_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_position'),
        ),
        migrations.AlterField(
            model_name='histo_images',
            name='parent',
            field=models.ForeignKey(db_column='histo_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.histo_header'),
        ),
        migrations.AlterField(
            model_name='linked_keys',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='linked_keys',
            name='key_word',
            field=models.ForeignKey(db_column='keyword', on_delete=django.db.models.deletion.CASCADE, to='analyses.Keyword'),
        ),
        migrations.AlterField(
            model_name='map_pickle',
            name='parent',
            field=models.ForeignKey(db_column='map_header', on_delete=django.db.models.deletion.CASCADE, to='analyses.map_header'),
        ),
        migrations.AlterField(
            model_name='normalization',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='overflow_underflow_histo',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='overflow_underflow_profile',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='profile1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='results_header',
            name='runcard',
            field=models.ForeignKey(db_column='runcard_name', default='', on_delete=django.db.models.deletion.CASCADE, to='analyses.runcard'),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='modelname',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='analyses.BSM_Model'),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='150820181433', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scatter1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='scatter2_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='scatter3_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.CASCADE, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='subpool',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='summary_text',
            name='parent',
            field=models.ForeignKey(db_column='dat_database', on_delete=django.db.models.deletion.CASCADE, to='analyses.dat_database'),
        ),
        migrations.AlterField(
            model_name='used_analyses',
            name='ana_name',
            field=models.ForeignKey(db_column='ana_name', on_delete=django.db.models.deletion.CASCADE, to='analyses.ana_list'),
        ),
        migrations.AlterField(
            model_name='used_analyses',
            name='modelname',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.CASCADE, to='analyses.BSM_Model'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='anaid',
            field=models.ForeignKey(db_column='anaid', on_delete=django.db.models.deletion.CASCADE, to='analyses.Analysis'),
        ),
    ]
