# Generated by Django 2.0.5 on 2018-07-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_auto_20180705_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='runcard_name',
            field=models.CharField(default='050720181215', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='histo1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='overflow_underflow_histo',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='overflow_underflow_profile',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='profile1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='runcard',
            name='runcard_name',
            field=models.CharField(default='050720181215', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scatter1_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='scatter2_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
        migrations.AlterField(
            model_name='scatter3_data',
            name='parent',
            field=models.ForeignKey(db_column='results_link', on_delete=django.db.models.deletion.DO_NOTHING, to='analyses.results_analyses'),
        ),
    ]
