#!/usr/bin/env python

import os
import glob
from argparse import ArgumentParser
from subprocess import call

class FindFiles(object):

    def __init__(self,directory):
        self.dir_path = directory
        self.file_list = []
        self.search()

    def search(self):
        for filename in glob.iglob(self.dir_path + '/**/*.yoda'):
            if "LHC" not in filename:
                self.file_list.append(filename)


class RunContur(object):

    def __init__(self,file_list,directory):
        self.file_list = file_list
        self.directory = directory
        self.CallContur()

    def CallContur(self):
        for filename in self.file_list:
            file = filename.split("/")
            file_local = file[-1]
            dir = ""
            for i in range(0,len(file)-1):
                dir = dir + "/" + file[i]
            dir = dir[1:]

            call(["contur", filename,"-o",dir+"/plots","-a",dir+"/ANALYSIS"])

            os.chdir(dir)
            call(["contur-mkhtml", file_local])
            os.chdir("../..")

if __name__ == "__main__":
    parser = ArgumentParser(description="Run full Contur for each yoda in directory")
    parser.add_argument('--directory', '-d',help='Directory to search in to find the specified data')
    arguments = parser.parse_args()

    files = FindFiles(arguments.directory)
    file_list = files.file_list
    run = RunContur(file_list,arguments.directory)
